title: MA563 Applied Dynamical Systems (Spring 2020)
baseurl: /MA563-S20
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
